/*
Deployment script for SpecialEducationPlanning


This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "SpecialEducationPlanning
"
:setvar DefaultFilePrefix "SpecialEducationPlanning
"
:setvar DefaultDataPath "C:\Users\vpastobe\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\vpastobe\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[__EFMigrationsHistory]...';


GO
CREATE TABLE [dbo].[__EFMigrationsHistory] (
    [MigrationId]    NVARCHAR (150) NOT NULL,
    [ProductVersion] NVARCHAR (32)  NOT NULL,
    CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED ([MigrationId] ASC)
);


GO
PRINT N'Creating [dbo].[AclGroup]...';


GO
CREATE TABLE [dbo].[AclGroup] (
    [Id]       INT IDENTITY (1, 1) NOT NULL,
    [RoleType] INT NOT NULL,
    CONSTRAINT [PK_AclGroup] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Action]...';


GO
CREATE TABLE [dbo].[Action] (
    [Id]             INT            IDENTITY (1, 1) NOT NULL,
    [ActionType]     INT            NOT NULL,
    [AdditionalInfo] NVARCHAR (MAX) NULL,
    [Date]           DATETIME2 (7)  NOT NULL,
    [EntityId]       INT            NOT NULL,
    [EntityName]     NVARCHAR (MAX) NULL,
    [User]           NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Action] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Area]...';


GO
CREATE TABLE [dbo].[Area] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [KeyName]  NVARCHAR (MAX) NULL,
    [RegionId] INT            NOT NULL,
    CONSTRAINT [PK_Area] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Area].[IX_Area_RegionId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Area_RegionId]
    ON [dbo].[Area]([RegionId] ASC);


GO
PRINT N'Creating [dbo].[AreaGroup]...';


GO
CREATE TABLE [dbo].[AreaGroup] (
    [Id]      INT IDENTITY (1, 1) NOT NULL,
    [AreaId]  INT NOT NULL,
    [GroupId] INT NOT NULL,
    CONSTRAINT [PK_AreaGroup] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[AreaGroup].[IX_AreaGroup_GroupId]...';


GO
CREATE NONCLUSTERED INDEX [IX_AreaGroup_GroupId]
    ON [dbo].[AreaGroup]([GroupId] ASC);


GO
PRINT N'Creating [dbo].[AreaGroup].[IX_AreaGroup_AreaId]...';


GO
CREATE NONCLUSTERED INDEX [IX_AreaGroup_AreaId]
    ON [dbo].[AreaGroup]([AreaId] ASC);


GO
PRINT N'Creating [dbo].[AuditLog]...';


GO
CREATE TABLE [dbo].[AuditLog] (
    [Id]            INT            IDENTITY (1, 1) NOT NULL,
    [DateTime]      DATETIME2 (7)  NOT NULL,
    [HttpQuery]     NVARCHAR (MAX) NULL,
    [LocalAddress]  NVARCHAR (MAX) NULL,
    [RemoteAddress] NVARCHAR (MAX) NULL,
    [User]          NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_AuditLog] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[BuilderEducationerAiep]...';


GO
CREATE TABLE [dbo].[BuilderEducationerAiep] (
    [Id]         INT IDENTITY (1, 1) NOT NULL,
    [BuilderId]  INT NOT NULL,
    [AiepId]    INT NOT NULL,
    [EducationerId] INT NOT NULL,
    CONSTRAINT [PK_BuilderEducationerAiep] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[BuilderEducationerAiep].[IX_BuilderEducationerAiep_BuilderId_AiepId_EducationerId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_BuilderEducationerAiep_BuilderId_AiepId_EducationerId]
    ON [dbo].[BuilderEducationerAiep]([BuilderId] ASC, [AiepId] ASC, [EducationerId] ASC);


GO
PRINT N'Creating [dbo].[BuilderEducationerAiep].[IX_BuilderEducationerAiep_EducationerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BuilderEducationerAiep_EducationerId]
    ON [dbo].[BuilderEducationerAiep]([EducationerId] ASC);


GO
PRINT N'Creating [dbo].[BuilderEducationerAiep].[IX_BuilderEducationerAiep_AiepId]...';


GO
CREATE NONCLUSTERED INDEX [IX_BuilderEducationerAiep_AiepId]
    ON [dbo].[BuilderEducationerAiep]([AiepId] ASC);


GO
PRINT N'Creating [dbo].[Comment]...';


GO
CREATE TABLE [dbo].[Comment] (
    [Id]         INT            IDENTITY (1, 1) NOT NULL,
    [Date]       DATETIME2 (7)  NOT NULL,
    [EntityId]   INT            NOT NULL,
    [EntityName] NVARCHAR (MAX) NULL,
    [LastModify] DATETIME2 (7)  NOT NULL,
    [Text]       NVARCHAR (MAX) NULL,
    [User]       NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Comment] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Country]...';


GO
CREATE TABLE [dbo].[Country] (
    [Id]      INT            IDENTITY (1, 1) NOT NULL,
    [KeyName] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[CountryGroup]...';


GO
CREATE TABLE [dbo].[CountryGroup] (
    [Id]        INT IDENTITY (1, 1) NOT NULL,
    [CountryId] INT NOT NULL,
    [GroupId]   INT NOT NULL,
    CONSTRAINT [PK_CountryGroup] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[CountryGroup].[IX_CountryGroup_GroupId]...';


GO
CREATE NONCLUSTERED INDEX [IX_CountryGroup_GroupId]
    ON [dbo].[CountryGroup]([GroupId] ASC);


GO
PRINT N'Creating [dbo].[CountryGroup].[IX_CountryGroup_CountryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_CountryGroup_CountryId]
    ON [dbo].[CountryGroup]([CountryId] ASC);


GO
PRINT N'Creating [dbo].[Aiep]...';


GO
CREATE TABLE [dbo].[Aiep] (
    [Id]            INT            IDENTITY (1, 1) NOT NULL,
    [Address1]      NVARCHAR (MAX) NULL,
    [Address2]      NVARCHAR (MAX) NULL,
    [Address3]      NVARCHAR (MAX) NULL,
    [Address4]      NVARCHAR (MAX) NULL,
    [Address5]      NVARCHAR (MAX) NULL,
    [Address6]      NVARCHAR (MAX) NULL,
    [AreaId]        INT            NOT NULL,
    [AiepCode]     NVARCHAR (MAX) NULL,
    [AiepNumber]   NVARCHAR (MAX) NULL,
    [DownloadLimit] INT            NOT NULL,
    [DownloadSpeed] INT            NOT NULL,
    [Email]         NVARCHAR (MAX) NULL,
    [FaxNumber]     NVARCHAR (MAX) NULL,
    [HtmlEmail]     NVARCHAR (MAX) NULL,
    [IpAddress]     NVARCHAR (MAX) NULL,
    [ManagerId]     INT            NOT NULL,
    [MediaServer]   NVARCHAR (MAX) NULL,
    [Name]          NVARCHAR (MAX) NULL,
    [PhoneNumber]   NVARCHAR (MAX) NULL,
    [Postcode]      NVARCHAR (MAX) NULL,
    [ReleaseInfoId] INT            NOT NULL,
    CONSTRAINT [PK_Aiep] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Aiep].[IX_Aiep_ReleaseInfoId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Aiep_ReleaseInfoId]
    ON [dbo].[Aiep]([ReleaseInfoId] ASC);


GO
PRINT N'Creating [dbo].[Aiep].[IX_Aiep_ManagerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Aiep_ManagerId]
    ON [dbo].[Aiep]([ManagerId] ASC);


GO
PRINT N'Creating [dbo].[Aiep].[IX_Aiep_AreaId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Aiep_AreaId]
    ON [dbo].[Aiep]([AreaId] ASC);


GO
PRINT N'Creating [dbo].[AiepGroup]...';


GO
CREATE TABLE [dbo].[AiepGroup] (
    [Id]      INT IDENTITY (1, 1) NOT NULL,
    [AiepId] INT NOT NULL,
    [GroupId] INT NOT NULL,
    CONSTRAINT [PK_AiepGroup] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[AiepGroup].[IX_AiepGroup_GroupId]...';


GO
CREATE NONCLUSTERED INDEX [IX_AiepGroup_GroupId]
    ON [dbo].[AiepGroup]([GroupId] ASC);


GO
PRINT N'Creating [dbo].[AiepGroup].[IX_AiepGroup_AiepId]...';


GO
CREATE NONCLUSTERED INDEX [IX_AiepGroup_AiepId]
    ON [dbo].[AiepGroup]([AiepId] ASC);


GO
PRINT N'Creating [dbo].[Group]...';


GO
CREATE TABLE [dbo].[Group] (
    [Id]      INT            IDENTITY (1, 1) NOT NULL,
    [KeyName] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Group] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GroupRole]...';


GO
CREATE TABLE [dbo].[GroupRole] (
    [Id]      INT IDENTITY (1, 1) NOT NULL,
    [GroupId] INT NOT NULL,
    [RoleId]  INT NOT NULL,
    CONSTRAINT [PK_GroupRole] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GroupRole].[IX_GroupRole_RoleId]...';


GO
CREATE NONCLUSTERED INDEX [IX_GroupRole_RoleId]
    ON [dbo].[GroupRole]([RoleId] ASC);


GO
PRINT N'Creating [dbo].[GroupRole].[IX_GroupRole_GroupId]...';


GO
CREATE NONCLUSTERED INDEX [IX_GroupRole_GroupId]
    ON [dbo].[GroupRole]([GroupId] ASC);


GO
PRINT N'Creating [dbo].[GroupUser]...';


GO
CREATE TABLE [dbo].[GroupUser] (
    [Id]      INT IDENTITY (1, 1) NOT NULL,
    [GroupId] INT NOT NULL,
    [UserId]  INT NOT NULL,
    CONSTRAINT [PK_GroupUser] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[GroupUser].[IX_GroupUser_UserId]...';


GO
CREATE NONCLUSTERED INDEX [IX_GroupUser_UserId]
    ON [dbo].[GroupUser]([UserId] ASC);


GO
PRINT N'Creating [dbo].[GroupUser].[IX_GroupUser_GroupId]...';


GO
CREATE NONCLUSTERED INDEX [IX_GroupUser_GroupId]
    ON [dbo].[GroupUser]([GroupId] ASC);


GO
PRINT N'Creating [dbo].[Permission]...';


GO
CREATE TABLE [dbo].[Permission] (
    [Id]    INT            IDENTITY (1, 1) NOT NULL,
    [AclId] INT            NOT NULL,
    [Name]  NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_Permission] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[PermissionRole]...';


GO
CREATE TABLE [dbo].[PermissionRole] (
    [Id]           INT IDENTITY (1, 1) NOT NULL,
    [PermissionId] INT NOT NULL,
    [UserRoleId]   INT NOT NULL,
    CONSTRAINT [PK_PermissionRole] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[PermissionRole].[IX_PermissionRole_UserRoleId]...';


GO
CREATE NONCLUSTERED INDEX [IX_PermissionRole_UserRoleId]
    ON [dbo].[PermissionRole]([UserRoleId] ASC);


GO
PRINT N'Creating [dbo].[PermissionRole].[IX_PermissionRole_PermissionId]...';


GO
CREATE NONCLUSTERED INDEX [IX_PermissionRole_PermissionId]
    ON [dbo].[PermissionRole]([PermissionId] ASC);


GO
PRINT N'Creating [dbo].[Plan]...';


GO
CREATE TABLE [dbo].[Plan] (
    [Id]                  INT            IDENTITY (1, 1) NOT NULL,
    [BuilderId]           INT            NULL,
    [Catalogue]           INT            NOT NULL,
    [CreationDate]        DATETIME2 (7)  NOT NULL,
    [DeletedDate]         DATETIME2 (7)  NULL,
    [DeletedUser]         NVARCHAR (MAX) NULL,
    [EducationerId]          INT            NULL,
    [EndUserAddress0]     NVARCHAR (MAX) NULL,
    [EndUserFirstName]    NVARCHAR (MAX) NULL,
    [EndUserFullName]     NVARCHAR (MAX) NULL,
    [EndUserId]           INT            NULL,
    [EndUserMobileNumber] NVARCHAR (MAX) NULL,
    [EndUserPostcode]     NVARCHAR (MAX) NULL,
    [EndUserSurname]      NVARCHAR (MAX) NULL,
    [IsDeleted]           BIT            NOT NULL,
    [IsStarred]           BIT            NOT NULL,
    [KeyName]             NVARCHAR (MAX) NULL,
    [LastModify]          DATETIME2 (7)  NOT NULL,
    [LastOpen]            DATETIME2 (7)  NOT NULL,
    [PlanCode]            NVARCHAR (MAX) NULL,
    [PlanState]           INT            NOT NULL,
    [ProjectId]           INT            NOT NULL,
    [SaleVersionId]       INT            NOT NULL,
    [Survey]              BIT            NOT NULL,
    [Title]               NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Plan] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Plan].[IX_Plan_ProjectId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Plan_ProjectId]
    ON [dbo].[Plan]([ProjectId] ASC);


GO
PRINT N'Creating [dbo].[Plan].[IX_Plan_EndUserId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Plan_EndUserId]
    ON [dbo].[Plan]([EndUserId] ASC);


GO
PRINT N'Creating [dbo].[Plan].[IX_Plan_EducationerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Plan_EducationerId]
    ON [dbo].[Plan]([EducationerId] ASC);


GO
PRINT N'Creating [dbo].[Plan].[IX_Plan_BuilderId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Plan_BuilderId]
    ON [dbo].[Plan]([BuilderId] ASC);


GO
PRINT N'Creating [dbo].[PlanGroup]...';


GO
CREATE TABLE [dbo].[PlanGroup] (
    [Id]      INT IDENTITY (1, 1) NOT NULL,
    [GroupId] INT NOT NULL,
    [PlanId]  INT NOT NULL,
    CONSTRAINT [PK_PlanGroup] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[PlanGroup].[IX_PlanGroup_PlanId]...';


GO
CREATE NONCLUSTERED INDEX [IX_PlanGroup_PlanId]
    ON [dbo].[PlanGroup]([PlanId] ASC);


GO
PRINT N'Creating [dbo].[PlanGroup].[IX_PlanGroup_GroupId]...';


GO
CREATE NONCLUSTERED INDEX [IX_PlanGroup_GroupId]
    ON [dbo].[PlanGroup]([GroupId] ASC);


GO
PRINT N'Creating [dbo].[Project]...';


GO
CREATE TABLE [dbo].[Project] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [CodeProject]       NVARCHAR (MAX) NULL,
    [CreationDate]      DATETIME2 (7)  NOT NULL,
    [AiepId]           INT            NULL,
    [KeyName]           NVARCHAR (MAX) NULL,
    [SinglePlanProject] BIT            NOT NULL,
    CONSTRAINT [PK_Project] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Project].[IX_Project_AiepId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Project_AiepId]
    ON [dbo].[Project]([AiepId] ASC);


GO
PRINT N'Creating [dbo].[ProjectGroup]...';


GO
CREATE TABLE [dbo].[ProjectGroup] (
    [Id]        INT IDENTITY (1, 1) NOT NULL,
    [GroupId]   INT NOT NULL,
    [ProjectId] INT NOT NULL,
    CONSTRAINT [PK_ProjectGroup] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProjectGroup].[IX_ProjectGroup_ProjectId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ProjectGroup_ProjectId]
    ON [dbo].[ProjectGroup]([ProjectId] ASC);


GO
PRINT N'Creating [dbo].[ProjectGroup].[IX_ProjectGroup_GroupId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ProjectGroup_GroupId]
    ON [dbo].[ProjectGroup]([GroupId] ASC);


GO
PRINT N'Creating [dbo].[Region]...';


GO
CREATE TABLE [dbo].[Region] (
    [Id]        INT            IDENTITY (1, 1) NOT NULL,
    [CountryId] INT            NOT NULL,
    [KeyName]   NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Region] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Region].[IX_Region_CountryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Region_CountryId]
    ON [dbo].[Region]([CountryId] ASC);


GO
PRINT N'Creating [dbo].[RegionGroup]...';


GO
CREATE TABLE [dbo].[RegionGroup] (
    [Id]       INT IDENTITY (1, 1) NOT NULL,
    [GroupId]  INT NOT NULL,
    [RegionId] INT NOT NULL,
    CONSTRAINT [PK_RegionGroup] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[RegionGroup].[IX_RegionGroup_RegionId]...';


GO
CREATE NONCLUSTERED INDEX [IX_RegionGroup_RegionId]
    ON [dbo].[RegionGroup]([RegionId] ASC);


GO
PRINT N'Creating [dbo].[RegionGroup].[IX_RegionGroup_GroupId]...';


GO
CREATE NONCLUSTERED INDEX [IX_RegionGroup_GroupId]
    ON [dbo].[RegionGroup]([GroupId] ASC);


GO
PRINT N'Creating [dbo].[ReleaseInfo]...';


GO
CREATE TABLE [dbo].[ReleaseInfo] (
    [Id]           INT            IDENTITY (1, 1) NOT NULL,
    [DateTime]     DATETIME2 (7)  NOT NULL,
    [Document]     NVARCHAR (MAX) NULL,
    [DocumentPath] NVARCHAR (MAX) NULL,
    [MajorVersion] INT            NOT NULL,
    [MinorVersion] INT            NOT NULL,
    [PatchVersion] INT            NOT NULL,
    [Subtitle]     NVARCHAR (MAX) NULL,
    [Title]        NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_ReleaseInfo] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Role]...';


GO
CREATE TABLE [dbo].[Role] (
    [Id]   INT            IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[RomItem]...';


GO
CREATE TABLE [dbo].[RomItem] (
    [Id]           INT            IDENTITY (1, 1) NOT NULL,
    [BuilderId]    INT            NOT NULL,
    [Colour]       NVARCHAR (MAX) NULL,
    [Quantity]     INT            NOT NULL,
    [Range]        NVARCHAR (MAX) NULL,
    [SerialNumber] NVARCHAR (MAX) NULL,
    [Sku]          NVARCHAR (MAX) NULL,
    [VersionId]    INT            NOT NULL,
    CONSTRAINT [PK_RomItem] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[RomItem].[IX_RomItem_VersionId]...';


GO
CREATE NONCLUSTERED INDEX [IX_RomItem_VersionId]
    ON [dbo].[RomItem]([VersionId] ASC);


GO
PRINT N'Creating [dbo].[TdpLog]...';


GO
CREATE TABLE [dbo].[TdpLog] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [Caller]            NVARCHAR (MAX) NULL,
    [Controller]        NVARCHAR (MAX) NULL,
    [Ip]                NVARCHAR (MAX) NULL,
    [Level]             NVARCHAR (MAX) NULL,
    [Message]           NVARCHAR (MAX) NULL,
    [ReceptionDateTime] DATETIME2 (7)  NOT NULL,
    [Time]              NVARCHAR (MAX) NULL,
    [User]              NVARCHAR (MAX) NULL,
    [UserName]          NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_TdpLog] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[User]...';


GO
CREATE TABLE [dbo].[User] (
    [AccountEmail]              NVARCHAR (MAX) NULL,
    [AccountNumber]             NVARCHAR (MAX) NULL,
    [CompanyName]               NVARCHAR (MAX) NULL,
    [ContactEmail]              NVARCHAR (MAX) NULL,
    [CountryCodeLandLineNumber] INT            NULL,
    [CountryCodeMobileNumber]   INT            NULL,
    [CreationDate]              DATETIME2 (7)  NULL,
    [EducationerName]              NVARCHAR (MAX) NULL,
    [FullName]                  NVARCHAR (MAX) NULL,
    [HouseNameorNumber]         NVARCHAR (MAX) NULL,
    [aiepurvey]              BIT            NULL,
    [Initials]                  NVARCHAR (MAX) NULL,
    [LandLineNumber]            NVARCHAR (MAX) NULL,
    [LastModify]                DATETIME2 (7)  NULL,
    [PlotReference]             NVARCHAR (MAX) NULL,
    [ReleaseInfoId]             INT            NULL,
    [CountryCode]               INT            NULL,
    [Id]                        INT            IDENTITY (1, 1) NOT NULL,
    [Address0]                  NVARCHAR (MAX) NULL,
    [Address1]                  NVARCHAR (MAX) NULL,
    [Address2]                  NVARCHAR (MAX) NULL,
    [Address3]                  NVARCHAR (MAX) NULL,
    [Address4]                  NVARCHAR (MAX) NULL,
    [Address5]                  NVARCHAR (MAX) NULL,
    [DeletedDate]               DATETIME2 (7)  NULL,
    [DeletedUser]               NVARCHAR (MAX) NULL,
    [Discriminator]             NVARCHAR (MAX) NOT NULL,
    [FirstName]                 NVARCHAR (20)  NULL,
    [IsDeleted]                 BIT            NOT NULL,
    [MobileNumber]              NVARCHAR (MAX) NULL,
    [Postcode]                  NVARCHAR (8)   NULL,
    [Surname]                   NVARCHAR (20)  NOT NULL,
    [Title]                     INT            NULL,
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[User].[IX_User_ReleaseInfoId]...';


GO
CREATE NONCLUSTERED INDEX [IX_User_ReleaseInfoId]
    ON [dbo].[User]([ReleaseInfoId] ASC);


GO
PRINT N'Creating [dbo].[Version]...';


GO
CREATE TABLE [dbo].[Version] (
    [Id]            INT            IDENTITY (1, 1) NOT NULL,
    [Catalog]       NVARCHAR (MAX) NULL,
    [Creation]      DATETIME2 (7)  NOT NULL,
    [KeyName]       NVARCHAR (MAX) NULL,
    [LastModify]    DATETIME2 (7)  NOT NULL,
    [PlanId]        INT            NOT NULL,
    [Preview]       NVARCHAR (MAX) NULL,
    [PreviewPath]   NVARCHAR (MAX) NULL,
    [Range]         NVARCHAR (MAX) NULL,
    [Rom]           NVARCHAR (MAX) NULL,
    [RomPath]       NVARCHAR (MAX) NULL,
    [SalePlanId]    INT            NULL,
    [VersionNotes]  NVARCHAR (MAX) NULL,
    [VersionNumber] INT            NOT NULL,
    CONSTRAINT [PK_Version] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Version].[IX_Version_SalePlanId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Version_SalePlanId]
    ON [dbo].[Version]([SalePlanId] ASC) WHERE ([SalePlanId] IS NOT NULL);


GO
PRINT N'Creating [dbo].[Version].[IX_Version_PlanId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Version_PlanId]
    ON [dbo].[Version]([PlanId] ASC);


GO
PRINT N'Creating [dbo].[PlanCodeSequence]...';


GO
CREATE SEQUENCE [dbo].[PlanCodeSequence]
    AS INT
    START WITH 10000
    INCREMENT BY 1
    MAXVALUE 99999
    CYCLE;


GO
PRINT N'Creating [dbo].[FK_Area_Region_RegionId]...';


GO
ALTER TABLE [dbo].[Area] WITH NOCHECK
    ADD CONSTRAINT [FK_Area_Region_RegionId] FOREIGN KEY ([RegionId]) REFERENCES [dbo].[Region] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_AreaGroup_Area_AreaId]...';


GO
ALTER TABLE [dbo].[AreaGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_AreaGroup_Area_AreaId] FOREIGN KEY ([AreaId]) REFERENCES [dbo].[Area] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_AreaGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[AreaGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_AreaGroup_Group_GroupId] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_BuilderEducationerAiep_Aiep_AiepId]...';


GO
ALTER TABLE [dbo].[BuilderEducationerAiep] WITH NOCHECK
    ADD CONSTRAINT [FK_BuilderEducationerAiep_Aiep_AiepId] FOREIGN KEY ([AiepId]) REFERENCES [dbo].[Aiep] ([Id]);


GO
PRINT N'Creating [dbo].[FK_BuilderEducationerAiep_User_BuilderId]...';


GO
ALTER TABLE [dbo].[BuilderEducationerAiep] WITH NOCHECK
    ADD CONSTRAINT [FK_BuilderEducationerAiep_User_BuilderId] FOREIGN KEY ([BuilderId]) REFERENCES [dbo].[User] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_BuilderEducationerAiep_User_EducationerId]...';


GO
ALTER TABLE [dbo].[BuilderEducationerAiep] WITH NOCHECK
    ADD CONSTRAINT [FK_BuilderEducationerAiep_User_EducationerId] FOREIGN KEY ([EducationerId]) REFERENCES [dbo].[User] ([Id]);


GO
PRINT N'Creating [dbo].[FK_CountryGroup_Country_CountryId]...';


GO
ALTER TABLE [dbo].[CountryGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_CountryGroup_Country_CountryId] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_CountryGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[CountryGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_CountryGroup_Group_GroupId] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Aiep_Area_AreaId]...';


GO
ALTER TABLE [dbo].[Aiep] WITH NOCHECK
    ADD CONSTRAINT [FK_Aiep_Area_AreaId] FOREIGN KEY ([AreaId]) REFERENCES [dbo].[Area] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Aiep_ReleaseInfo_ReleaseInfoId]...';


GO
ALTER TABLE [dbo].[Aiep] WITH NOCHECK
    ADD CONSTRAINT [FK_Aiep_ReleaseInfo_ReleaseInfoId] FOREIGN KEY ([ReleaseInfoId]) REFERENCES [dbo].[ReleaseInfo] ([Id]);


GO
PRINT N'Creating [dbo].[FK_Aiep_User_ManagerId]...';


GO
ALTER TABLE [dbo].[Aiep] WITH NOCHECK
    ADD CONSTRAINT [FK_Aiep_User_ManagerId] FOREIGN KEY ([ManagerId]) REFERENCES [dbo].[User] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_AiepGroup_Aiep_AiepId]...';


GO
ALTER TABLE [dbo].[AiepGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_AiepGroup_Aiep_AiepId] FOREIGN KEY ([AiepId]) REFERENCES [dbo].[Aiep] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_AiepGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[AiepGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_AiepGroup_Group_GroupId] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GroupRole_AclGroup_RoleId]...';


GO
ALTER TABLE [dbo].[GroupRole] WITH NOCHECK
    ADD CONSTRAINT [FK_GroupRole_AclGroup_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[AclGroup] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GroupRole_Group_GroupId]...';


GO
ALTER TABLE [dbo].[GroupRole] WITH NOCHECK
    ADD CONSTRAINT [FK_GroupRole_Group_GroupId] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GroupUser_Group_GroupId]...';


GO
ALTER TABLE [dbo].[GroupUser] WITH NOCHECK
    ADD CONSTRAINT [FK_GroupUser_Group_GroupId] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GroupUser_User_UserId]...';


GO
ALTER TABLE [dbo].[GroupUser] WITH NOCHECK
    ADD CONSTRAINT [FK_GroupUser_User_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_PermissionRole_Permission_PermissionId]...';


GO
ALTER TABLE [dbo].[PermissionRole] WITH NOCHECK
    ADD CONSTRAINT [FK_PermissionRole_Permission_PermissionId] FOREIGN KEY ([PermissionId]) REFERENCES [dbo].[Permission] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_PermissionRole_Role_UserRoleId]...';


GO
ALTER TABLE [dbo].[PermissionRole] WITH NOCHECK
    ADD CONSTRAINT [FK_PermissionRole_Role_UserRoleId] FOREIGN KEY ([UserRoleId]) REFERENCES [dbo].[Role] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Plan_Project_ProjectId]...';


GO
ALTER TABLE [dbo].[Plan] WITH NOCHECK
    ADD CONSTRAINT [FK_Plan_Project_ProjectId] FOREIGN KEY ([ProjectId]) REFERENCES [dbo].[Project] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Plan_User_BuilderId]...';


GO
ALTER TABLE [dbo].[Plan] WITH NOCHECK
    ADD CONSTRAINT [FK_Plan_User_BuilderId] FOREIGN KEY ([BuilderId]) REFERENCES [dbo].[User] ([Id]);


GO
PRINT N'Creating [dbo].[FK_Plan_User_EducationerId]...';


GO
ALTER TABLE [dbo].[Plan] WITH NOCHECK
    ADD CONSTRAINT [FK_Plan_User_EducationerId] FOREIGN KEY ([EducationerId]) REFERENCES [dbo].[User] ([Id]);


GO
PRINT N'Creating [dbo].[FK_Plan_User_EndUserId]...';


GO
ALTER TABLE [dbo].[Plan] WITH NOCHECK
    ADD CONSTRAINT [FK_Plan_User_EndUserId] FOREIGN KEY ([EndUserId]) REFERENCES [dbo].[User] ([Id]);


GO
PRINT N'Creating [dbo].[FK_PlanGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[PlanGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_PlanGroup_Group_GroupId] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_PlanGroup_Plan_PlanId]...';


GO
ALTER TABLE [dbo].[PlanGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_PlanGroup_Plan_PlanId] FOREIGN KEY ([PlanId]) REFERENCES [dbo].[Plan] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Project_Aiep_AiepId]...';


GO
ALTER TABLE [dbo].[Project] WITH NOCHECK
    ADD CONSTRAINT [FK_Project_Aiep_AiepId] FOREIGN KEY ([AiepId]) REFERENCES [dbo].[Aiep] ([Id]);


GO
PRINT N'Creating [dbo].[FK_ProjectGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[ProjectGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectGroup_Group_GroupId] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_ProjectGroup_Project_ProjectId]...';


GO
ALTER TABLE [dbo].[ProjectGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectGroup_Project_ProjectId] FOREIGN KEY ([ProjectId]) REFERENCES [dbo].[Project] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Region_Country_CountryId]...';


GO
ALTER TABLE [dbo].[Region] WITH NOCHECK
    ADD CONSTRAINT [FK_Region_Country_CountryId] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_RegionGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[RegionGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_RegionGroup_Group_GroupId] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_RegionGroup_Region_RegionId]...';


GO
ALTER TABLE [dbo].[RegionGroup] WITH NOCHECK
    ADD CONSTRAINT [FK_RegionGroup_Region_RegionId] FOREIGN KEY ([RegionId]) REFERENCES [dbo].[Region] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_RomItem_Version_VersionId]...';


GO
ALTER TABLE [dbo].[RomItem] WITH NOCHECK
    ADD CONSTRAINT [FK_RomItem_Version_VersionId] FOREIGN KEY ([VersionId]) REFERENCES [dbo].[Version] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_User_ReleaseInfo_ReleaseInfoId]...';


GO
ALTER TABLE [dbo].[User] WITH NOCHECK
    ADD CONSTRAINT [FK_User_ReleaseInfo_ReleaseInfoId] FOREIGN KEY ([ReleaseInfoId]) REFERENCES [dbo].[ReleaseInfo] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Version_Plan_PlanId]...';


GO
ALTER TABLE [dbo].[Version] WITH NOCHECK
    ADD CONSTRAINT [FK_Version_Plan_PlanId] FOREIGN KEY ([PlanId]) REFERENCES [dbo].[Plan] ([Id]);


GO
PRINT N'Creating [dbo].[FK_Version_Plan_SalePlanId]...';


GO
ALTER TABLE [dbo].[Version] WITH NOCHECK
    ADD CONSTRAINT [FK_Version_Plan_SalePlanId] FOREIGN KEY ([SalePlanId]) REFERENCES [dbo].[Plan] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Area] WITH CHECK CHECK CONSTRAINT [FK_Area_Region_RegionId];

ALTER TABLE [dbo].[AreaGroup] WITH CHECK CHECK CONSTRAINT [FK_AreaGroup_Area_AreaId];

ALTER TABLE [dbo].[AreaGroup] WITH CHECK CHECK CONSTRAINT [FK_AreaGroup_Group_GroupId];

ALTER TABLE [dbo].[BuilderEducationerAiep] WITH CHECK CHECK CONSTRAINT [FK_BuilderEducationerAiep_Aiep_AiepId];

ALTER TABLE [dbo].[BuilderEducationerAiep] WITH CHECK CHECK CONSTRAINT [FK_BuilderEducationerAiep_User_BuilderId];

ALTER TABLE [dbo].[BuilderEducationerAiep] WITH CHECK CHECK CONSTRAINT [FK_BuilderEducationerAiep_User_EducationerId];

ALTER TABLE [dbo].[CountryGroup] WITH CHECK CHECK CONSTRAINT [FK_CountryGroup_Country_CountryId];

ALTER TABLE [dbo].[CountryGroup] WITH CHECK CHECK CONSTRAINT [FK_CountryGroup_Group_GroupId];

ALTER TABLE [dbo].[Aiep] WITH CHECK CHECK CONSTRAINT [FK_Aiep_Area_AreaId];

ALTER TABLE [dbo].[Aiep] WITH CHECK CHECK CONSTRAINT [FK_Aiep_ReleaseInfo_ReleaseInfoId];

ALTER TABLE [dbo].[Aiep] WITH CHECK CHECK CONSTRAINT [FK_Aiep_User_ManagerId];

ALTER TABLE [dbo].[AiepGroup] WITH CHECK CHECK CONSTRAINT [FK_AiepGroup_Aiep_AiepId];

ALTER TABLE [dbo].[AiepGroup] WITH CHECK CHECK CONSTRAINT [FK_AiepGroup_Group_GroupId];

ALTER TABLE [dbo].[GroupRole] WITH CHECK CHECK CONSTRAINT [FK_GroupRole_AclGroup_RoleId];

ALTER TABLE [dbo].[GroupRole] WITH CHECK CHECK CONSTRAINT [FK_GroupRole_Group_GroupId];

ALTER TABLE [dbo].[GroupUser] WITH CHECK CHECK CONSTRAINT [FK_GroupUser_Group_GroupId];

ALTER TABLE [dbo].[GroupUser] WITH CHECK CHECK CONSTRAINT [FK_GroupUser_User_UserId];

ALTER TABLE [dbo].[PermissionRole] WITH CHECK CHECK CONSTRAINT [FK_PermissionRole_Permission_PermissionId];

ALTER TABLE [dbo].[PermissionRole] WITH CHECK CHECK CONSTRAINT [FK_PermissionRole_Role_UserRoleId];

ALTER TABLE [dbo].[Plan] WITH CHECK CHECK CONSTRAINT [FK_Plan_Project_ProjectId];

ALTER TABLE [dbo].[Plan] WITH CHECK CHECK CONSTRAINT [FK_Plan_User_BuilderId];

ALTER TABLE [dbo].[Plan] WITH CHECK CHECK CONSTRAINT [FK_Plan_User_EducationerId];

ALTER TABLE [dbo].[Plan] WITH CHECK CHECK CONSTRAINT [FK_Plan_User_EndUserId];

ALTER TABLE [dbo].[PlanGroup] WITH CHECK CHECK CONSTRAINT [FK_PlanGroup_Group_GroupId];

ALTER TABLE [dbo].[PlanGroup] WITH CHECK CHECK CONSTRAINT [FK_PlanGroup_Plan_PlanId];

ALTER TABLE [dbo].[Project] WITH CHECK CHECK CONSTRAINT [FK_Project_Aiep_AiepId];

ALTER TABLE [dbo].[ProjectGroup] WITH CHECK CHECK CONSTRAINT [FK_ProjectGroup_Group_GroupId];

ALTER TABLE [dbo].[ProjectGroup] WITH CHECK CHECK CONSTRAINT [FK_ProjectGroup_Project_ProjectId];

ALTER TABLE [dbo].[Region] WITH CHECK CHECK CONSTRAINT [FK_Region_Country_CountryId];

ALTER TABLE [dbo].[RegionGroup] WITH CHECK CHECK CONSTRAINT [FK_RegionGroup_Group_GroupId];

ALTER TABLE [dbo].[RegionGroup] WITH CHECK CHECK CONSTRAINT [FK_RegionGroup_Region_RegionId];

ALTER TABLE [dbo].[RomItem] WITH CHECK CHECK CONSTRAINT [FK_RomItem_Version_VersionId];

ALTER TABLE [dbo].[User] WITH CHECK CHECK CONSTRAINT [FK_User_ReleaseInfo_ReleaseInfoId];

ALTER TABLE [dbo].[Version] WITH CHECK CHECK CONSTRAINT [FK_Version_Plan_PlanId];

ALTER TABLE [dbo].[Version] WITH CHECK CHECK CONSTRAINT [FK_Version_Plan_SalePlanId];


GO
PRINT N'Update complete.';


GO


