/*
Deployment script for SpecialEducationPlanning


This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "SpecialEducationPlanning
"
:setvar DefaultFilePrefix "SpecialEducationPlanning
"
:setvar DefaultDataPath "C:\Users\vpastobe\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\vpastobe\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
Table [dbo].[__EFMigrationsHistory] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[__EFMigrationsHistory])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[AclGroup] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[AclGroup])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Action] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Action])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Area] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Area])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[AreaGroup] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[AreaGroup])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[AuditLog] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[AuditLog])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[BuilderEducationerAiep] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[BuilderEducationerAiep])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Comment] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Comment])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Country] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Country])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[CountryGroup] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[CountryGroup])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Aiep] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Aiep])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[AiepGroup] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[AiepGroup])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Group] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Group])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[GroupRole] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[GroupRole])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[GroupUser] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[GroupUser])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Permission] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Permission])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[PermissionRole] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[PermissionRole])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Plan] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Plan])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[PlanGroup] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[PlanGroup])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Project] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Project])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[ProjectGroup] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[ProjectGroup])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Region] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Region])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[RegionGroup] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[RegionGroup])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[ReleaseInfo] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[ReleaseInfo])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Role] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Role])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[RomItem] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[RomItem])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[TdpLog] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[TdpLog])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[User] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[User])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
Table [dbo].[Version] is being dropped.  Deployment will halt if the table contains data.
*/

IF EXISTS (select top 1 1 from [dbo].[Version])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping [dbo].[FK_GroupRole_AclGroup_RoleId]...';


GO
ALTER TABLE [dbo].[GroupRole] DROP CONSTRAINT [FK_GroupRole_AclGroup_RoleId];


GO
PRINT N'Dropping [dbo].[FK_AreaGroup_Area_AreaId]...';


GO
ALTER TABLE [dbo].[AreaGroup] DROP CONSTRAINT [FK_AreaGroup_Area_AreaId];


GO
PRINT N'Dropping [dbo].[FK_Aiep_Area_AreaId]...';


GO
ALTER TABLE [dbo].[Aiep] DROP CONSTRAINT [FK_Aiep_Area_AreaId];


GO
PRINT N'Dropping [dbo].[FK_Region_Country_CountryId]...';


GO
ALTER TABLE [dbo].[Region] DROP CONSTRAINT [FK_Region_Country_CountryId];


GO
PRINT N'Dropping [dbo].[FK_CountryGroup_Country_CountryId]...';


GO
ALTER TABLE [dbo].[CountryGroup] DROP CONSTRAINT [FK_CountryGroup_Country_CountryId];


GO
PRINT N'Dropping [dbo].[FK_BuilderEducationerAiep_Aiep_AiepId]...';


GO
ALTER TABLE [dbo].[BuilderEducationerAiep] DROP CONSTRAINT [FK_BuilderEducationerAiep_Aiep_AiepId];


GO
PRINT N'Dropping [dbo].[FK_AiepGroup_Aiep_AiepId]...';


GO
ALTER TABLE [dbo].[AiepGroup] DROP CONSTRAINT [FK_AiepGroup_Aiep_AiepId];


GO
PRINT N'Dropping [dbo].[FK_Project_Aiep_AiepId]...';


GO
ALTER TABLE [dbo].[Project] DROP CONSTRAINT [FK_Project_Aiep_AiepId];


GO
PRINT N'Dropping [dbo].[FK_CountryGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[CountryGroup] DROP CONSTRAINT [FK_CountryGroup_Group_GroupId];


GO
PRINT N'Dropping [dbo].[FK_GroupRole_Group_GroupId]...';


GO
ALTER TABLE [dbo].[GroupRole] DROP CONSTRAINT [FK_GroupRole_Group_GroupId];


GO
PRINT N'Dropping [dbo].[FK_RegionGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[RegionGroup] DROP CONSTRAINT [FK_RegionGroup_Group_GroupId];


GO
PRINT N'Dropping [dbo].[FK_GroupUser_Group_GroupId]...';


GO
ALTER TABLE [dbo].[GroupUser] DROP CONSTRAINT [FK_GroupUser_Group_GroupId];


GO
PRINT N'Dropping [dbo].[FK_AreaGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[AreaGroup] DROP CONSTRAINT [FK_AreaGroup_Group_GroupId];


GO
PRINT N'Dropping [dbo].[FK_AiepGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[AiepGroup] DROP CONSTRAINT [FK_AiepGroup_Group_GroupId];


GO
PRINT N'Dropping [dbo].[FK_ProjectGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[ProjectGroup] DROP CONSTRAINT [FK_ProjectGroup_Group_GroupId];


GO
PRINT N'Dropping [dbo].[FK_PlanGroup_Group_GroupId]...';


GO
ALTER TABLE [dbo].[PlanGroup] DROP CONSTRAINT [FK_PlanGroup_Group_GroupId];


GO
PRINT N'Dropping [dbo].[FK_PermissionRole_Permission_PermissionId]...';


GO
ALTER TABLE [dbo].[PermissionRole] DROP CONSTRAINT [FK_PermissionRole_Permission_PermissionId];


GO
PRINT N'Dropping [dbo].[FK_PlanGroup_Plan_PlanId]...';


GO
ALTER TABLE [dbo].[PlanGroup] DROP CONSTRAINT [FK_PlanGroup_Plan_PlanId];


GO
PRINT N'Dropping [dbo].[FK_Version_Plan_PlanId]...';


GO
ALTER TABLE [dbo].[Version] DROP CONSTRAINT [FK_Version_Plan_PlanId];


GO
PRINT N'Dropping [dbo].[FK_Version_Plan_SalePlanId]...';


GO
ALTER TABLE [dbo].[Version] DROP CONSTRAINT [FK_Version_Plan_SalePlanId];


GO
PRINT N'Dropping [dbo].[FK_Plan_Project_ProjectId]...';


GO
ALTER TABLE [dbo].[Plan] DROP CONSTRAINT [FK_Plan_Project_ProjectId];


GO
PRINT N'Dropping [dbo].[FK_ProjectGroup_Project_ProjectId]...';


GO
ALTER TABLE [dbo].[ProjectGroup] DROP CONSTRAINT [FK_ProjectGroup_Project_ProjectId];


GO
PRINT N'Dropping [dbo].[FK_Area_Region_RegionId]...';


GO
ALTER TABLE [dbo].[Area] DROP CONSTRAINT [FK_Area_Region_RegionId];


GO
PRINT N'Dropping [dbo].[FK_RegionGroup_Region_RegionId]...';


GO
ALTER TABLE [dbo].[RegionGroup] DROP CONSTRAINT [FK_RegionGroup_Region_RegionId];


GO
PRINT N'Dropping [dbo].[FK_User_ReleaseInfo_ReleaseInfoId]...';


GO
ALTER TABLE [dbo].[User] DROP CONSTRAINT [FK_User_ReleaseInfo_ReleaseInfoId];


GO
PRINT N'Dropping [dbo].[FK_Aiep_ReleaseInfo_ReleaseInfoId]...';


GO
ALTER TABLE [dbo].[Aiep] DROP CONSTRAINT [FK_Aiep_ReleaseInfo_ReleaseInfoId];


GO
PRINT N'Dropping [dbo].[FK_PermissionRole_Role_UserRoleId]...';


GO
ALTER TABLE [dbo].[PermissionRole] DROP CONSTRAINT [FK_PermissionRole_Role_UserRoleId];


GO
PRINT N'Dropping [dbo].[FK_GroupUser_User_UserId]...';


GO
ALTER TABLE [dbo].[GroupUser] DROP CONSTRAINT [FK_GroupUser_User_UserId];


GO
PRINT N'Dropping [dbo].[FK_Aiep_User_ManagerId]...';


GO
ALTER TABLE [dbo].[Aiep] DROP CONSTRAINT [FK_Aiep_User_ManagerId];


GO
PRINT N'Dropping [dbo].[FK_BuilderEducationerAiep_User_BuilderId]...';


GO
ALTER TABLE [dbo].[BuilderEducationerAiep] DROP CONSTRAINT [FK_BuilderEducationerAiep_User_BuilderId];


GO
PRINT N'Dropping [dbo].[FK_BuilderEducationerAiep_User_EducationerId]...';


GO
ALTER TABLE [dbo].[BuilderEducationerAiep] DROP CONSTRAINT [FK_BuilderEducationerAiep_User_EducationerId];


GO
PRINT N'Dropping [dbo].[FK_Plan_User_BuilderId]...';


GO
ALTER TABLE [dbo].[Plan] DROP CONSTRAINT [FK_Plan_User_BuilderId];


GO
PRINT N'Dropping [dbo].[FK_Plan_User_EducationerId]...';


GO
ALTER TABLE [dbo].[Plan] DROP CONSTRAINT [FK_Plan_User_EducationerId];


GO
PRINT N'Dropping [dbo].[FK_Plan_User_EndUserId]...';


GO
ALTER TABLE [dbo].[Plan] DROP CONSTRAINT [FK_Plan_User_EndUserId];


GO
PRINT N'Dropping [dbo].[FK_RomItem_Version_VersionId]...';


GO
ALTER TABLE [dbo].[RomItem] DROP CONSTRAINT [FK_RomItem_Version_VersionId];


GO
PRINT N'Dropping [dbo].[__EFMigrationsHistory]...';


GO
DROP TABLE [dbo].[__EFMigrationsHistory];


GO
PRINT N'Dropping [dbo].[AclGroup]...';


GO
DROP TABLE [dbo].[AclGroup];


GO
PRINT N'Dropping [dbo].[Action]...';


GO
DROP TABLE [dbo].[Action];


GO
PRINT N'Dropping [dbo].[Area]...';


GO
DROP TABLE [dbo].[Area];


GO
PRINT N'Dropping [dbo].[AreaGroup]...';


GO
DROP TABLE [dbo].[AreaGroup];


GO
PRINT N'Dropping [dbo].[AuditLog]...';


GO
DROP TABLE [dbo].[AuditLog];


GO
PRINT N'Dropping [dbo].[BuilderEducationerAiep]...';


GO
DROP TABLE [dbo].[BuilderEducationerAiep];


GO
PRINT N'Dropping [dbo].[Comment]...';


GO
DROP TABLE [dbo].[Comment];


GO
PRINT N'Dropping [dbo].[Country]...';


GO
DROP TABLE [dbo].[Country];


GO
PRINT N'Dropping [dbo].[CountryGroup]...';


GO
DROP TABLE [dbo].[CountryGroup];


GO
PRINT N'Dropping [dbo].[Aiep]...';


GO
DROP TABLE [dbo].[Aiep];


GO
PRINT N'Dropping [dbo].[AiepGroup]...';


GO
DROP TABLE [dbo].[AiepGroup];


GO
PRINT N'Dropping [dbo].[Group]...';


GO
DROP TABLE [dbo].[Group];


GO
PRINT N'Dropping [dbo].[GroupRole]...';


GO
DROP TABLE [dbo].[GroupRole];


GO
PRINT N'Dropping [dbo].[GroupUser]...';


GO
DROP TABLE [dbo].[GroupUser];


GO
PRINT N'Dropping [dbo].[Permission]...';


GO
DROP TABLE [dbo].[Permission];


GO
PRINT N'Dropping [dbo].[PermissionRole]...';


GO
DROP TABLE [dbo].[PermissionRole];


GO
PRINT N'Dropping [dbo].[Plan]...';


GO
DROP TABLE [dbo].[Plan];


GO
PRINT N'Dropping [dbo].[PlanGroup]...';


GO
DROP TABLE [dbo].[PlanGroup];


GO
PRINT N'Dropping [dbo].[Project]...';


GO
DROP TABLE [dbo].[Project];


GO
PRINT N'Dropping [dbo].[ProjectGroup]...';


GO
DROP TABLE [dbo].[ProjectGroup];


GO
PRINT N'Dropping [dbo].[Region]...';


GO
DROP TABLE [dbo].[Region];


GO
PRINT N'Dropping [dbo].[RegionGroup]...';


GO
DROP TABLE [dbo].[RegionGroup];


GO
PRINT N'Dropping [dbo].[ReleaseInfo]...';


GO
DROP TABLE [dbo].[ReleaseInfo];


GO
PRINT N'Dropping [dbo].[Role]...';


GO
DROP TABLE [dbo].[Role];


GO
PRINT N'Dropping [dbo].[RomItem]...';


GO
DROP TABLE [dbo].[RomItem];


GO
PRINT N'Dropping [dbo].[TdpLog]...';


GO
DROP TABLE [dbo].[TdpLog];


GO
PRINT N'Dropping [dbo].[User]...';


GO
DROP TABLE [dbo].[User];


GO
PRINT N'Dropping [dbo].[Version]...';


GO
DROP TABLE [dbo].[Version];


GO
PRINT N'Dropping [dbo].[PlanCodeSequence]...';


GO
DROP SEQUENCE [dbo].[PlanCodeSequence];


GO
PRINT N'Update complete.';


GO


