//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialEducationPlanning
.Api.ConnectedServices.SAP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aiep.com/EducationViewInternational", ConfigurationName="SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_Out")]
    public interface MI_1519_DV_SAPC_Request_Intl_Out
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_OutResponse> MI_1519_DV_SAPC_Request_Intl_OutAsync(SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_OutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aiep.com/EducationViewInternational")]
    public partial class DT_1519_DV_SAPC_Request_Intl
    {
        
        private DT_1519_DV_SAPC_Request_IntlCustRecon custReconField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_1519_DV_SAPC_Request_IntlCustRecon CustRecon
        {
            get
            {
                return this.custReconField;
            }
            set
            {
                this.custReconField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aiep.com/EducationViewInternational")]
    public partial class DT_1519_DV_SAPC_Request_IntlCustRecon
    {
        
        private string max_address_returnField;
        
        private DT_1519_DV_SAPC_Request_IntlCustReconAddresses[] addressesField;
        
        private DT_1519_DV_SAPC_Request_Intl_AccNum[] accNumbersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Max_address_return
        {
            get
            {
                return this.max_address_returnField;
            }
            set
            {
                this.max_address_returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Addresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_1519_DV_SAPC_Request_IntlCustReconAddresses[] Addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccNumbers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_1519_DV_SAPC_Request_Intl_AccNum[] AccNumbers
        {
            get
            {
                return this.accNumbersField;
            }
            set
            {
                this.accNumbersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aiep.com/EducationViewInternational")]
    public partial class DT_1519_DV_SAPC_Request_IntlCustReconAddresses
    {
        
        private string record_noField;
        
        private string companyField;
        
        private string address1Field;
        
        private string postcodeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Record_no
        {
            get
            {
                return this.record_noField;
            }
            set
            {
                this.record_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aiep.com/EducationViewInternational")]
    public partial class DT_1519_SAPC_DV_CustDetails_Intl
    {
        
        private string record_noField;
        
        private string companyField;
        
        private string countryField;
        
        private string nameField;
        
        private string tradingNameField;
        
        private string postcodeField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string accountNumberField;
        
        private string emailField;
        
        private string diallingCodeField;
        
        private string landLineNumberField;
        
        private string mobileNumberField;
        
        private string builderStatusField;
        
        private string idField;
        
        private string AiepIDField;
        
        private string AiepNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Record_no
        {
            get
            {
                return this.record_noField;
            }
            set
            {
                this.record_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TradingName
        {
            get
            {
                return this.tradingNameField;
            }
            set
            {
                this.tradingNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Address3
        {
            get
            {
                return this.address3Field;
            }
            set
            {
                this.address3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DiallingCode
        {
            get
            {
                return this.diallingCodeField;
            }
            set
            {
                this.diallingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string LandLineNumber
        {
            get
            {
                return this.landLineNumberField;
            }
            set
            {
                this.landLineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string MobileNumber
        {
            get
            {
                return this.mobileNumberField;
            }
            set
            {
                this.mobileNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string BuilderStatus
        {
            get
            {
                return this.builderStatusField;
            }
            set
            {
                this.builderStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=15)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string AiepID
        {
            get
            {
                return this.AiepIDField;
            }
            set
            {
                this.AiepIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string AiepName
        {
            get
            {
                return this.AiepNameField;
            }
            set
            {
                this.AiepNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aiep.com/EducationViewInternational")]
    public partial class DT_1519_DV_SAPC_BAPIRET2_Intl
    {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private string rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO
        {
            get
            {
                return this.lOG_NOField;
            }
            set
            {
                this.lOG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO
        {
            get
            {
                return this.lOG_MSG_NOField;
            }
            set
            {
                this.lOG_MSG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1
        {
            get
            {
                return this.mESSAGE_V1Field;
            }
            set
            {
                this.mESSAGE_V1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2
        {
            get
            {
                return this.mESSAGE_V2Field;
            }
            set
            {
                this.mESSAGE_V2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3
        {
            get
            {
                return this.mESSAGE_V3Field;
            }
            set
            {
                this.mESSAGE_V3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4
        {
            get
            {
                return this.mESSAGE_V4Field;
            }
            set
            {
                this.mESSAGE_V4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER
        {
            get
            {
                return this.pARAMETERField;
            }
            set
            {
                this.pARAMETERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ROW
        {
            get
            {
                return this.rOWField;
            }
            set
            {
                this.rOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD
        {
            get
            {
                return this.fIELDField;
            }
            set
            {
                this.fIELDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM
        {
            get
            {
                return this.sYSTEMField;
            }
            set
            {
                this.sYSTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aiep.com/EducationViewInternational")]
    public partial class DT_1519_DV_SAPC_Request_Intl_Resp
    {
        
        private DT_1519_DV_SAPC_BAPIRET2_Intl returnField;
        
        private DT_1519_SAPC_DV_CustDetails_Intl[] custDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_1519_DV_SAPC_BAPIRET2_Intl Return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_1519_SAPC_DV_CustDetails_Intl[] CustDetails
        {
            get
            {
                return this.custDetailsField;
            }
            set
            {
                this.custDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aiep.com/EducationViewInternational")]
    public partial class DT_1519_DV_SAPC_Request_Intl_AccNum
    {
        
        private string companyField;
        
        private string accNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AccNumber
        {
            get
            {
                return this.accNumberField;
            }
            set
            {
                this.accNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MI_1519_DV_SAPC_Request_Intl_OutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aiep.com/EducationViewInternational", Order=0)]
        public SpecialEducationPlanning
.Api.ConnectedServices.SAP.DT_1519_DV_SAPC_Request_Intl MT_1519_DV_SAPC_Request_Intl;
        
        public MI_1519_DV_SAPC_Request_Intl_OutRequest()
        {
        }
        
        public MI_1519_DV_SAPC_Request_Intl_OutRequest(SpecialEducationPlanning
.Api.ConnectedServices.SAP.DT_1519_DV_SAPC_Request_Intl MT_1519_DV_SAPC_Request_Intl)
        {
            this.MT_1519_DV_SAPC_Request_Intl = MT_1519_DV_SAPC_Request_Intl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MI_1519_DV_SAPC_Request_Intl_OutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aiep.com/EducationViewInternational", Order=0)]
        public SpecialEducationPlanning
.Api.ConnectedServices.SAP.DT_1519_DV_SAPC_Request_Intl_Resp MT_1519_DV_SAPC_Request_Intl_Resp;
        
        public MI_1519_DV_SAPC_Request_Intl_OutResponse()
        {
        }
        
        public MI_1519_DV_SAPC_Request_Intl_OutResponse(SpecialEducationPlanning
.Api.ConnectedServices.SAP.DT_1519_DV_SAPC_Request_Intl_Resp MT_1519_DV_SAPC_Request_Intl_Resp)
        {
            this.MT_1519_DV_SAPC_Request_Intl_Resp = MT_1519_DV_SAPC_Request_Intl_Resp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface MI_1519_DV_SAPC_Request_Intl_OutChannel : SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_Out, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MI_1519_DV_SAPC_Request_Intl_OutClient : System.ServiceModel.ClientBase<SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_Out>, SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_Out
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MI_1519_DV_SAPC_Request_Intl_OutClient(EndpointConfiguration endpointConfiguration) : 
                base(MI_1519_DV_SAPC_Request_Intl_OutClient.GetBindingForEndpoint(endpointConfiguration), MI_1519_DV_SAPC_Request_Intl_OutClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MI_1519_DV_SAPC_Request_Intl_OutClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MI_1519_DV_SAPC_Request_Intl_OutClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MI_1519_DV_SAPC_Request_Intl_OutClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MI_1519_DV_SAPC_Request_Intl_OutClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MI_1519_DV_SAPC_Request_Intl_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_OutResponse> SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_Out.MI_1519_DV_SAPC_Request_Intl_OutAsync(SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_OutRequest request)
        {
            return base.Channel.MI_1519_DV_SAPC_Request_Intl_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_OutResponse> MI_1519_DV_SAPC_Request_Intl_OutAsync(SpecialEducationPlanning
.Api.ConnectedServices.SAP.DT_1519_DV_SAPC_Request_Intl MT_1519_DV_SAPC_Request_Intl)
        {
            SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_OutRequest inValue = new SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_OutRequest();
            inValue.MT_1519_DV_SAPC_Request_Intl = MT_1519_DV_SAPC_Request_Intl;
            return ((SpecialEducationPlanning
.Api.ConnectedServices.SAP.MI_1519_DV_SAPC_Request_Intl_Out)(this)).MI_1519_DV_SAPC_Request_Intl_OutAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress(@"http://dl1183.eur-d.howdev.corp:50000/XISOAPAdapter/MessageServlet?senderParty=EducationView&senderService=BC_EducationView&receiverParty=&receiverService=&interface=MI_1519_DV_SAPC_Request_Intl_Out&interfaceNamespace=http%3A%2F%2Faiep.com%2FEducationViewInternational");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress(@"https://dl1183.eur-d.howdev.corp:50001/XISOAPAdapter/MessageServlet?senderParty=EducationView&senderService=BC_EducationView&receiverParty=&receiverService=&interface=MI_1519_DV_SAPC_Request_Intl_Out&interfaceNamespace=http%3A%2F%2Faiep.com%2FEducationViewInternational");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}


