stages:
#### UK
- template: docker/stages/deploy_database_schema_stage.yaml@templates
  parameters:
    StageName:                DBUPDATE_UK_PREPRD
    VariableGroups:           ['preprd-uk-tdp']
    DependsOn:                ['APP_UK_QA']
    Environment:              tdp-preprd
    AgentPool:                'aiep Trade Windows NonPrd UKS - VMSS'
    BuildArtifactName:        $(database_artifact_name)
    ServiceConnection:        hjs-trade-preprd-001-app-svc
    ConnectionString:         $(kvs-ConnectionStrings-DefaultConnectionString)
    DACPACFile:               'bin/Release/SpecialEducationPlanning
.Database.dacpac'
    BlockOnPossibleDataLoss:  $(BlockOnPossibleDataLoss)
    DatabaseEdition:          $(DatabaseEdition)
    DatabaseServiceObjective: $(DatabaseServiceObjective)
    KeyVaultName:             kvuktdppreprduks001

- template: docker/stages/deploy_kubernetes_secrets_stage.yaml@templates
  parameters:
    StageName:            APP_SECRETS_UK_PREPRD
    VariableGroups:       ['preprd-uk-tdp','preprd-uk-tdp-appsettings']
    DependsOn:            ['Build_and_Push_Image','DBUPDATE_UK_PREPRD']
    Environment:          tdp-preprd
    AgentPool:            'aiep Trade Linux NonPrd UKS - VMSS'
    BuildArtifactName:    $(artifact_name)
    AKSServiceConnection: aks-akstdpakspreprduks001-svc
    ServiceConnection:    hjs-trade-preprd-001-app-svc
    KeyVaultName:         kvuktdppreprduks001
    TlsCertificateFile:   $(tls_cert_file)
    TlsKeyFile:           $(tls_key_file)
    TlsSecretName:        $(tls_secret_name)
    Namespace:            $(namespace)
    SecretsFile:          $(app_settings_file)
    SecretsName:          $(app_settings_name)

- template: docker/stages/deploy_kubernetes_helm_chart_stage.yaml@templates
  parameters:
    StageName:            APP_UK_PREPRD
    VariableGroups:       ['Educationview-common','preprd-uk-tdp']
    DependsOn:            ['APP_SECRETS_UK_PREPRD']
    Environment:          tdp-preprd
    AgentPool:            'aiep Trade Linux NonPrd UKS - VMSS'
    BuildArtifactName:    $(artifact_name)
    AKSServiceConnection: aks-akstdpakspreprduks001-svc
    ServiceConnection:    hjs-trade-preprd-001-app-svc
    ChartName:            tdp-preprd
    ChartPath:            deployment/tdp-api
    Namespace:            $(namespace)
    ValuesFile:           deployment/tdp-api/values.yaml
    KeyVaultName:         kvuktdppreprduks001
    PAT:                  $(AdoPatToken)
    Organization:         $(AdoOrganization)
    ProjectName:          $(AdoProject)
    LibraryGroupName:     'build-details'
    BranchVariableName:   'preprd-uk-api-branch'
    BuildIdVariableName:  'preprd-uk-api-buildId'

#### FRA
- template: docker/stages/deploy_database_schema_stage.yaml@templates
  parameters:
    StageName:                DBUPDATE_FRA_PREPRD
    VariableGroups:           ['preprd-fra-tdp']
    DependsOn:                ['APP_FRA_QA']
    Environment:              tdp-preprd
    AgentPool:                'aiep Trade Windows NonPrd UKS - VMSS'
    BuildArtifactName:        $(database_artifact_name)
    ServiceConnection:        hjs-trade-preprd-001-app-svc
    ConnectionString:         $(kvs-ConnectionStrings-DefaultConnectionString)
    DACPACFile:               'bin/Release/SpecialEducationPlanning
.Database.dacpac'
    BlockOnPossibleDataLoss:  $(BlockOnPossibleDataLoss)
    DatabaseEdition:          $(DatabaseEdition)
    DatabaseServiceObjective: $(DatabaseServiceObjective)
    KeyVaultName:             kvfratdppreprduks001

- template: docker/stages/deploy_kubernetes_secrets_stage.yaml@templates
  parameters:
    StageName:            APP_SECRETS_FRA_PREPRD
    VariableGroups:       ['preprd-fra-tdp','preprd-fra-tdp-appsettings']
    DependsOn:            ['Build_and_Push_Image','DBUPDATE_FRA_PREPRD']
    Environment:          tdp-preprd
    AgentPool:            'aiep Trade Linux NonPrd UKS - VMSS'
    BuildArtifactName:    $(artifact_name)
    AKSServiceConnection: aks-akstdpakspreprduks001-svc
    ServiceConnection:    hjs-trade-preprd-001-app-svc
    KeyVaultName:         kvfratdppreprduks001
    TlsCertificateFile:   $(tls_cert_file)
    TlsKeyFile:           $(tls_key_file)
    TlsSecretName:        $(tls_secret_name)
    Namespace:            $(namespace)
    SecretsFile:          $(app_settings_file)
    SecretsName:          $(app_settings_name)

- template: docker/stages/deploy_kubernetes_helm_chart_stage.yaml@templates
  parameters:
    StageName:            APP_FRA_PREPRD
    VariableGroups:       ['Educationview-common','preprd-fra-tdp']
    DependsOn:            ['APP_SECRETS_FRA_PREPRD']
    Environment:          tdp-preprd
    AgentPool:            'aiep Trade Linux NonPrd UKS - VMSS'
    BuildArtifactName:    $(artifact_name)
    AKSServiceConnection: aks-akstdpakspreprduks001-svc
    ServiceConnection:    hjs-trade-preprd-001-app-svc
    ChartName:            fra-tdp-preprd
    ChartPath:            deployment/tdp-api
    Namespace:            $(namespace)
    ValuesFile:           deployment/tdp-api/values.yaml
    KeyVaultName:         kvfratdppreprduks001
    PAT:                  $(AdoPatToken)
    Organization:         $(AdoOrganization)
    ProjectName:          $(AdoProject)
    LibraryGroupName:     'build-details'
    BranchVariableName:   'preprd-fra-api-branch'
    BuildIdVariableName:  'preprd-fra-api-buildId'

#### ROI
- template: docker/stages/deploy_database_schema_stage.yaml@templates
  parameters:
    StageName:                DBUPDATE_ROI_PREPRD
    VariableGroups:           ['preprd-roi-tdp']
    DependsOn:                ['APP_ROI_QA']
    Environment:              tdp-preprd
    AgentPool:                'aiep Trade Windows NonPrd UKS - VMSS'
    BuildArtifactName:        $(database_artifact_name)
    ServiceConnection:        hjs-trade-preprd-001-app-svc
    ConnectionString:         $(kvs-ConnectionStrings-DefaultConnectionString)
    DACPACFile:               'bin/Release/SpecialEducationPlanning
.Database.dacpac'
    BlockOnPossibleDataLoss:  $(BlockOnPossibleDataLoss)
    DatabaseEdition:          $(DatabaseEdition)
    DatabaseServiceObjective: $(DatabaseServiceObjective)
    KeyVaultName:             kvroitdppreprduks001

- template: docker/stages/deploy_kubernetes_secrets_stage.yaml@templates
  parameters:
    StageName:            APP_SECRETS_ROI_PREPRD
    VariableGroups:       ['preprd-roi-tdp','preprd-roi-tdp-appsettings']
    DependsOn:            ['Build_and_Push_Image','DBUPDATE_ROI_PREPRD']
    Environment:          tdp-preprd
    AgentPool:            'aiep Trade Linux NonPrd UKS - VMSS'
    BuildArtifactName:    $(artifact_name)
    AKSServiceConnection: aks-akstdpakspreprduks001-svc
    ServiceConnection:    hjs-trade-preprd-001-app-svc
    KeyVaultName:         kvroitdppreprduks001
    TlsCertificateFile:   $(tls_cert_file)
    TlsKeyFile:           $(tls_key_file)
    TlsSecretName:        $(tls_secret_name)
    Namespace:            $(namespace)
    SecretsFile:          $(app_settings_file)
    SecretsName:          $(app_settings_name)

- template: docker/stages/deploy_kubernetes_helm_chart_stage.yaml@templates
  parameters:
    StageName:            APP_ROI_PREPRD
    VariableGroups:       ['Educationview-common','preprd-roi-tdp']
    DependsOn:            ['APP_SECRETS_ROI_PREPRD']
    Environment:          tdp-preprd
    AgentPool:            'aiep Trade Linux NonPrd UKS - VMSS'
    BuildArtifactName:    $(artifact_name)
    AKSServiceConnection: aks-akstdpakspreprduks001-svc
    ServiceConnection:    hjs-trade-preprd-001-app-svc
    ChartName:            roi-tdp-preprd
    ChartPath:            deployment/tdp-api
    Namespace:            $(namespace)
    ValuesFile:           deployment/tdp-api/values.yaml
    KeyVaultName:         kvroitdppreprduks001
    PAT:                  $(AdoPatToken)
    Organization:         $(AdoOrganization)
    ProjectName:          $(AdoProject)
    LibraryGroupName:     'build-details'
    BranchVariableName:   'preprd-roi-api-branch'
    BuildIdVariableName:  'preprd-roi-api-buildId'
