trigger: none

schedules:
- cron: "0 19 * * 1-5"  # Runs at 7pm UTC Mon - Fri
  displayName: "Daily Backend CI Build"
  branches:
    include:
    - develop
  always: true

resources:
  repositories:
  - repository: templates
    type: git
    name: 'aiep Core/aiep.core.azdo.templates'
    ref: feature/Educationview_templates

name: $(Build.DefinitionName)_$(Date:ddMMyyyy)$(Rev:.r)

variables:
- name:  artifact_name
  value: 'Educationviewci'


extends:
  template: docker/base/base_template.yaml@templates
  parameters:
    BuildStages:

    - template: docker/stages/build_net_8_app_stage.yaml@templates
      parameters:
        VariableGroups:   []
        StageName:        'Build_and_Push_Image'
        AgentPool:        'aiep Trade Linux NonPrd UKS - VMSS'
        Project:          SpecialEducationPlanning
/SpecialEducationPlanning
.Api.Host/*.csproj
        NugetFeed:        '800e42bd-640c-4531-9216-2ccd562a596d'
        UnitTestProject:  '**/*.Test.csproj'
        WorkingDirectory: $(System.DefaultWorkingDirectory)
        # DotNetVersion:
        # vsVersion:

    - template: docker/stages/build_database_schema_stage.yaml@templates
      parameters:
        VariableGroups: []
        StageName:         'Build_Database_Schema'
        AgentPool:         'aiep Trade Windows NonPrd UKS - VMSS'
        WorkingDirectory:  $(System.DefaultWorkingDirectory)
        DatabaseProject:   SpecialEducationPlanning
/SpecialEducationPlanning
.Database/SpecialEducationPlanning
.Database.sqlproj
        PublishArtifact:   'false'


