SET IDENTITY_INSERT [dbo].[Catalog] ON
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (1, N'Kitchens', N'1458299216', NULL, 1)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (2, N'Linear', N'1497616168', NULL, 1)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (3,'Appliances','1460020676',NULL,0)
INSERT  [dbo].[Catalog]	([Id], [Name], [Code], [Range], [Enabled]) VALUES (4,'Sinks','1460020677',NULL,0)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (5,'Plan Technique','792368500',NULL,0)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (6,'Revêtement de sol','1554806387',NULL,0)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (7,'Lighting','1400749520',NULL,0)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (8,'Advanced Graphics','1011025654',NULL,0)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (9,'European Base File','1077010400',NULL,0)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (10,'Kitchens(OLD)','1210340078',NULL,0)
INSERT  [dbo].[Catalog]	([Id], [Name], [Code], [Range], [Enabled]) VALUES (11,'Appliances(OLD)','1187345969',NULL,0)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (12,'Sinks(OLD)','1188482952',NULL,0)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (13,'Bathroom(OLD)','1202122586',NULL,0)
INSERT  [dbo].[Catalog] ([Id], [Name], [Code], [Range], [Enabled]) VALUES (14,'Revêtement de sol(OLD)','1237287925',NULL,0)
INSERT  [dbo].[Catalog]	([Id], [Name], [Code], [Range], [Enabled]) VALUES (15,'Drawn Appliance Base File','1054799972',NULL,0)
SET IDENTITY_INSERT [dbo].[Catalog] OFF

-- TITLE
INSERT [dbo].[Title] ([Id], [TitleName]) VALUES (1,N'Mr')
INSERT [dbo].[Title] ([Id], [TitleName]) VALUES (2,N'MM.')
INSERT [dbo].[Title] ([Id], [TitleName]) VALUES (3,N'Mme')
INSERT [dbo].[Title] ([Id], [TitleName]) VALUES (4,N'Mmes')
INSERT [dbo].[Title] ([Id], [TitleName]) VALUES (5,N'Mlle')
INSERT [dbo].[Title] ([Id], [TitleName]) VALUES (6,N'Mlles')
INSERT [dbo].[Title] ([Id], [TitleName]) VALUES (7,N'Mr & Mr');
INSERT [dbo].[Title] ([Id], [TitleName]) VALUES (8,N'Mme & Mme');
INSERT [dbo].[Title] ([Id], [TitleName]) VALUES (9,N'Mx');

-- Remove plan_publish permission from roles
DELETE FROM permissionrole
FROM permissionrole INNER JOIN permission ON permission.id = PermissionRole.PermissionId
WHERE permission.Name = 'Plan_Publish'

-- COUNTRY
INSERT [dbo].[Country] ([KeyName]) VALUES (N'France')
DECLARE @CountryId INT = (SELECT Id FROM [dbo].[Country] WHERE [KeyName] = 'France')

-- REGIONS
INSERT [dbo].[Region] ([CountryId], [KeyName]) VALUES (@CountryId, N'PAR')
INSERT [dbo].[Region] ([CountryId], [KeyName]) VALUES (@CountryId, N'PRO')
INSERT [dbo].[Region] ([CountryId], [KeyName]) VALUES (@CountryId, N'PROV')

DECLARE @region1 INT = (SELECT Id FROM [dbo].[Region] WHERE [KeyName] = 'PAR')
DECLARE @region2 INT = (SELECT Id FROM [dbo].[Region] WHERE [KeyName] = 'PRO')
DECLARE @region3 INT = (SELECT Id FROM [dbo].[Region] WHERE [KeyName] = 'PROV')

-- AREAS
INSERT [dbo].[Area] ([RegionId], [KeyName]) VALUES (@region1, N'HWF_PAR1')
INSERT [dbo].[Area] ([RegionId], [KeyName]) VALUES (@region1, N'HWF_PAR2')
INSERT [dbo].[Area] ([RegionId], [KeyName]) VALUES (@region2, N'HWF_CENTO')
INSERT [dbo].[Area] ([RegionId], [KeyName]) VALUES (@region2, N'HWF_NORD')
INSERT [dbo].[Area] ([RegionId], [KeyName]) VALUES (@region2, N'HWF_SUDEST')
INSERT [dbo].[Area] ([RegionId], [KeyName]) VALUES (@region3, N'HWBD_NORD')

DECLARE @area1 INT = (SELECT Id FROM [dbo].[Area] WHERE [KeyName] = 'HWF_PAR1')
DECLARE @area2 INT = (SELECT Id FROM [dbo].[Area] WHERE [KeyName] = 'HWF_PAR2')
DECLARE @area3 INT = (SELECT Id FROM [dbo].[Area] WHERE [KeyName] = 'HWF_CENTO')
DECLARE @area4 INT = (SELECT Id FROM [dbo].[Area] WHERE [KeyName] = 'HWF_NORD')
DECLARE @area5 INT = (SELECT Id FROM [dbo].[Area] WHERE [KeyName] = 'HWF_SUDEST')
DECLARE @area6 INT = (SELECT Id FROM [dbo].[Area] WHERE [KeyName] = 'HWBD_NORD')

-- AiepS
INSERT [dbo].[Aiep] ([releaseinfoid], [Aiepcode], [areaid], [name], [email], [address1], [address2], [address3], [address4], [address5], [address6], [postcode], [phonenumber], [faxnumber], [ipaddress], [mediaserver], [htmlemail], [downloadspeed], [downloadlimit], [managerid], [createddate], [creationuser], [updateddate], [updateuser]) VALUES (NULL, N'321F', @area1, N'Morangis', N'morangis@aiep.com', N'2 avenue Ferdinand de Lesseps', NULL, N'Morangis', NULL, NULL, NULL, N'91420', NULL, NULL, NULL, NULL, 0, 0, 0, NULL,Cast(N'2019-03-26T08:59:15.5633333' AS DATETIME2), N'testUserCreate', Cast(N'2019-03-26T08:59:15.5633333' AS DATETIME2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([releaseinfoid], [Aiepcode], [areaid], [name], [email], [address1], [address2], [address3], [address4], [address5], [address6], [postcode], [phonenumber], [faxnumber], [ipaddress], [mediaserver], [htmlemail], [downloadspeed], [downloadlimit], [managerid], [createddate], [creationuser], [updateddate], [updateuser]) VALUES (NULL, N'329F', @area1, N'Ivry sur Seine', N'Ivry@aiep.com', N'102 avenue Jean Jaurès', NULL, N'Ivry-Sur-Seine', NULL, NULL, NULL, N'94200', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, Cast(N'2019-03-26T08:59:15.5633333' AS DATETIME2), N'testUserCreate', Cast(N'2019-03-26T08:59:15.5633333' AS DATETIME2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'331F', @area1, N'VilleJust', N'villejust@aiep.com', N'32 Avenue de l''Oceanie', NULL,N'Villejust', NULL, NULL, NULL, N'91140', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'332F', @area1, N'Coignieres', N'coignieres@aiep.com', N'16 Rue des Louveries', NULL, N'Coignières', NULL, NULL, NULL, N'78310', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'335F', @area1, N'Lagny Sur Marne', N'lagny@aiep.com', N'72 Rue Jacquard', NULL, N'Lagny-Sur-Marne', NULL, NULL, NULL, N'77400', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'336F', @area1, N'Massy', N'massy@aiep.com', N'16-34 Rue du Buisson aux Fraises', NULL, N'Massy', NULL, NULL, NULL, N'91400', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'338F', @area1, N'Servon', N'servon@aiep.com', N'19 Route nationale', N'Zone du Poirier Penche Bât B' , N'Servon', NULL, NULL, NULL, N'77170', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'341F', @area1, N'Melun', N'melun@aiep.com', N'4 rue de la Plaine de la Croix Bernaud', NULL, N'Vaux-Le-Penil', NULL, NULL, NULL, N'77000', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'343F', @area1, N'Fleury', N'Fleury@aiep.com', N'21 rue Clément ADER', NULL, N'Fleury Merogis', NULL, NULL, NULL, N'91700', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'301F', @area2, N'Aubervilliers', N'aubervilliers@aiep.com', N'204/208 Boulevard Félix Faure', NULL, N'Aubervilliers', NULL, NULL, NULL, N'93300', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'308F', @area2, N'Bezons', N'bezons@aiep.com', N'11 rue Guy Moquet', NULL, N'Bezons', NULL, NULL, NULL, N'95871', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'318F', @area2, N'Argenteuil', N'argenteuil@aiep.com', N'11 rue Guy Moquet', NULL, N'Argenteuil', NULL, NULL, NULL, N'95100', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'334F', @area2, N'Noisy Le Sec', N'noisy@aiep.com', N'74 Rue de Paris', NULL, N'Noisy-Le-Sec', NULL, NULL, NULL, N'93130', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'337F', @area2, N'Buchelay', N'buchelay@aiep.com', N'8 Rue des Gamelines', NULL, N'Buchelay', NULL, NULL, NULL, N'78200', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'339F', @area2, N'Villeneuve La Garenne', N'villeneuve@aiep.com', N'36, Rue Avenue Marc Sangnier - Bat B', NULL, N'Villeneuve La Garenne', NULL, NULL, NULL, N'92390', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'340F', @area2, N'Pierrelaye', N'Pierrelaye@aiep.com', N'2 Chemin du parc', NULL, N'Pierrelaye', NULL, NULL, NULL, N'95480', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'345F', @area2, N'Conflans', N'Conflans@aiep.com', N'5, rue de l''Hautil', N'Bat B - Urban Valley', N'Conflans Saint Honorine', NULL, NULL, NULL, N'78700', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'346F', @area2, N'Champigny', N'champigny@aiep.com', N'Rue Alexandre Fourmy', NULL, N'Champigny Sur Marne', NULL, NULL, NULL, N'94500', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'306F', @area3, N'Chartres Luisant', N'chartres@aiep.com', N'15 Rue Jean Perrin', NULL, N'Luisant', NULL, NULL, NULL, N'28600', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'311F', @area3, N'Rouen', N'rouen@aiep.com', N'Entrée Rue de la Grande Epine - 30/31 Boulevard Lénine', N'ZI Est du bord de Seine', N'Saint Etienne de Rouvray', NULL, NULL, NULL, N'76800', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'319F', @area3, N'Orleans', N'orleans@aiep.com', N'2 rue Lavoisier', NULL, N'Ingre', NULL, NULL, NULL, N'45140', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'322F', @area3, N'Le Mans', N'lemans@aiep.com', N'57 rue Pierre Piffault', NULL, N'Le Mans', NULL, NULL, NULL, N'72000', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'326F', @area3, N'Caen', N'caen@aiep.com', N'Allée du Bac', N'Cours Montalivet', N'Mondeville', NULL, NULL, NULL, N'14120', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'310F', @area4, N'Arras', N'arras@aiep.com', N'35/39 Avenue Roger Salengro', NULL, N'Saint Laurent Blangy', NULL, NULL, NULL, N'62223', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'314F', @area4, N'Douai', N'douai@aiep.com', N'557 rue Maurice Caullery', NULL, N'Douai', NULL, NULL, NULL, N'59500', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'315F', @area4, N'Amiens', N'amiens@aiep.com', N'Rue Héléne Boucher', NULL, N'Rivery', NULL, NULL, NULL, N'80136', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'317F', @area4, N'Wasquehal', N'wasquehal@aiep.com', N'6 Rue du Houblon', NULL, N'WASQUEHAL', NULL, NULL, NULL, N'59290', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'323F', @area4, N'Cambrai', N'cambrai@aiep.com', N'Avenue de l''europe', N'ZI Fontaine notre dame', N'Fontaine Notre Dame', NULL, NULL, NULL, N'59400', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'324F', @area4, N'Boulogne Sur Mer', N'boulogne@aiep.com', N'15 rue Pierre MARTIN', NULL, N'Saint-Martin-Boulogne', NULL, NULL, NULL, N'62280', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'333F', @area4, N'Armentieres', N'armentieres@aiep.com', N'4 Rue Ambroise Paré', NULL, N'Bois Grenier', NULL, NULL, NULL, N'59280', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'327F', @area5, N'Vitrolles', N'vitrolles@aiep.com', N'15 Bis Avenue de Rome', NULL, N'Vitrolles', NULL, NULL, NULL, N'13127', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'328F', @area5, N'St Priest', N'Lyon@aiep.com', N'198 route de Grenoble', NULL, N'Saint Priest', NULL, NULL, NULL, N'69800', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'344F', @area5, N'Arnas', N'Arnas@aiep.com', N'Route des Frênes', N'Bat 2 ZAC de Joux', N'Arnas', NULL, NULL, NULL, N'69400', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'348F', @area5, N'Aubagne', N'aubagne@aiep.com', N'514 Avenue de la Fleuride',  N'ZI les Paluds', N'Aubagne', NULL, NULL, NULL, N'13400', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'349F', @area5, N'Dardilly', N'dardilly@aiep.com', N'16 Chemin des Hirondelles', N'Zac du Paisy lot 15 et 16', N'Dardilly', NULL, NULL, NULL, N'69570', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'351F', @area5, N'Aix les Milles', N'aix@aiep.com', N'405 rue Louis Berton',  'Pole d''activite d''Aix en Provence', N'Aix En Provence', NULL, NULL, NULL, N'13290', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'4001', @area6, N'Charleroi', N'charleroi@aiep.com', N'Rue des Emailleries, 4', NULL, N'Gosselies', NULL, NULL, NULL, N'B-6041', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([ReleaseInfoId], [AiepCode], [AreaId], [Name], [Email], [Address1], [Address2], [Address3], [Address4], [Address5], [Address6], [Postcode], [PhoneNumber], [FaxNumber], [IpAddress], [MediaServer], [HtmlEmail], [DownloadSpeed], [DownloadLimit], [ManagerId], [CreatedDate], [CreationUser], [UpdatedDate], [UpdateUser]) VALUES (NULL, N'4002', @area6, N'Liege', N'liege@aiep.com', N'Rue de Wallonie, 9A', NULL, N'Grace Hollogne', NULL, NULL, NULL, N'B-4460', NULL, NULL, NULL, NULL, 0, 0, 0, NULL, CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserCreate', CAST(N'2019-03-26T08:59:15.5633333' AS DateTime2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([releaseinfoid], [Aiepcode], [areaid], [name], [email], [address1], [address2], [address3], [address4], [address5], [address6], [postcode], [phonenumber], [faxnumber], [ipaddress], [mediaserver], [htmlemail], [downloadspeed], [downloadlimit], [managerid], [createddate], [creationuser], [updateddate], [updateuser]) VALUES (NULL, N'342F', @area2, N'Groslay', N'groslay@aiep.com', N'Bédu Bat C', N'3 rue Magnier', N'Groslay', NULL, NULL, NULL, N'95410', NULL, NULL, NULL, NULL, 0, 0, 0, NULL,Cast(N'2019-03-26T08:59:15.5633333' AS DATETIME2), N'testUserCreate', Cast(N'2019-03-26T08:59:15.5633333' AS DATETIME2), N'testUserUpdate')
INSERT [dbo].[Aiep] ([releaseinfoid], [Aiepcode], [areaid], [name], [email], [address1], [address2], [address3], [address4], [address5], [address6], [postcode], [phonenumber], [faxnumber], [ipaddress], [mediaserver], [htmlemail], [downloadspeed], [downloadlimit], [managerid], [createddate], [creationuser], [updateddate], [updateuser]) VALUES (NULL, N'352F', @area1, N'Bonneuil', N'bonneuil@aiep.com', N'10, avenue des Coquelicots Bat 4', NULL, N'Bonneuil sur Marne', NULL, NULL, NULL, N'94380', NULL, NULL, NULL, NULL, 0, 0, 0, NULL,Cast(N'2019-03-26T08:59:15.5633333' AS DATETIME2), N'testUserCreate', Cast(N'2019-03-26T08:59:15.5633333' AS DATETIME2), N'testUserUpdate')

